version: '3'

services:

  # ==== Application ====

  app:
    image: ghcr.io/rasouza/steammy-bot:main
    volumes:
        # - ./database:/app/database
        - ./logs/:/app/logs
        - ./assets:/app/assets
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TEST_GUILD_ID=${TEST_GUILD_ID}
      - BOT_OWNER_ID=${BOT_OWNER_ID}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - API_PORT=${API_PORT}
      - API_ADMIN_TOKEN=${API_ADMIN_TOKEN}
    # depends_on:
    #   - database

  
  # ==== PostgreSQL database ====

  database:
    image: postgres
    container_name: database
    restart: always
    volumes:
      - ./data:/var/lib/postgresql:rw
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 5432:5432

  # ==== MySQL database ====

  # database:
  #   image: mysql # or `mariadb`
  #   container_name: database
  #   restart: always
  #   volumes:
  #     - ./data:/var/lib/mysql:rw
  #   environment:
  #     - MYSQL_DATABASE=${DATABASE_NAME}
  #     - MYSQL_USER=${DATABASE_USER}
  #     - MYSQL_PASSWORD=${DATABASE_PASSWORD}
  #     - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
  #   ports:
  #     - 3306:3306