name: Build

on:
  push:
    branches: [ main ]

  pull_request:

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # allow the workflow to be re-used in other workflows
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Node.js dependencies
        run: npm ci --ignore-scripts

      - name: Check formatting
        run: npx prettier --check "src/**/*.ts" "test/**/*.ts"

      - name: Type check
        run: npm run type:check

      - name: Run linters
        run: npx eslint "{src,apps,libs,test}/**/*.ts"

      - name: Build
        run: npm run build

      - name: Run unit tests
        run: npm run test

      - name: Run e2e tests
        run: npm run test:e2e
